wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    t:
      1:
      - 3
      4: 3.8.9
      5: 0.11.0
      8:
      - 5
